{{- if .Values.serviceAccount.propel.create -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "kubera-propel.serviceAccountName" . }}
  labels: {{- include "kubera-propel.chartMetaLabel" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
{{- end }}
