apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubera-propel.fullname" . }}-server
  labels:
    {{- include "kubera-propel.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: propel-server
      nodePort: 31000
      port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.port }}
    - name: propel-server-auth
      port: 9003
      targetPort: 3000
  selector:
    {{- include "kubera-propel.server.matchLabels" . | nindent 4 }}
