apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    propel.kubera.mayadata.io/app-name: propel-webapp
    propel.kubera.mayadata.io/is-server: "true"
  name: propel-webapp
  namespace: kubera.namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      propel.kubera.mayadata.io/app-name: propel-webapp
      propel.kubera.mayadata.io/is-server: "true"
  template:
    metadata:
      labels:
        propel.kubera.mayadata.io/app-name: propel-webapp
        propel.kubera.mayadata.io/is-server: "true"
    spec:
      containers:
      - image: kubera.image.registry/kubera-propel-webapp:{{kubera.build_image_tag}}
        imagePullPolicy: Always
        name: propel-webapp
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: kubera.imagePullSecret
      serviceAccountName: kubera.product.serviceAccount
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    propel.kubera.mayadata.io/app-name: propel-server
    propel.kubera.mayadata.io/is-server: "true"
  name: propel-server
  namespace: kubera.namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      propel.kubera.mayadata.io/app-name: propel-server
      propel.kubera.mayadata.io/is-server: "true"
  template:
    metadata:
      labels:
        propel.kubera.mayadata.io/app-name: propel-server
        propel.kubera.mayadata.io/is-server: "true"
    spec:
      containers:
      - env:
        - name: JWT_SECRET
          value: kubera.jwt_secret
        - name: EXTERNAL_ADDRESS
          value: ""
        - name: PROPEL_SERVER_ADDRESS
          value: http://propel-server:9002
        - name: FRONTEND_URL
          value: http://propel-webapp:9091
        - name: CORE_URL
          value: kubera.core.url
        - name: SELF_CLUSTER
          value: "true"
        - name: PROPEL_AGENT_SUBSCRIBER_IMAGE
          value: kubera.image.registry/kubera-propel-agent-subscriber:{{kubera.build_image_tag}}
        - name: PROPEL_AGENT_CONTROLLER_IMAGE
          value: kubera.image.registry/kubera-propel-agent-controller:{{kubera.build_image_tag}}
        - name: PROPEL_AGENT_SERVICE_ACCOUNT_NAME
          value: propel
        - name: PROPEL_IMAGE_PULL_SECRET
          value: kubera.imagePullSecret
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: kubera.common_config
        - configMapRef:
            name: kubera.agent_gateway_config
        image: kubera.image.registry/kubera-propel-server:{{kubera.build_image_tag}}
        imagePullPolicy: Always
        name: propel-server
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: kubera.imagePullSecret
      serviceAccountName: kubera.product.serviceAccount
---
apiVersion: v1
kind: Service
metadata:
  labels:
    propel.kubera.mayadata.io/app-name: propel-webapp
    propel.kubera.mayadata.io/is-server: "true"
  name: propel-webapp
  namespace: kubera.namespace
spec:
  ports:
  - name: propel-webapp
    nodePort: 31002
    port: 9091
    targetPort: 8080
  selector:
    propel.kubera.mayadata.io/app-name: propel-webapp
    propel.kubera.mayadata.io/is-server: "true"
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    propel.kubera.mayadata.io/app-name: propel-server
    propel.kubera.mayadata.io/is-server: "true"
  name: propel-server
  namespace: kubera.namespace
spec:
  ports:
  - name: propel-server
    nodePort: 31000
    port: 9002
    targetPort: 8080
  - name: propel-server-auth
    port: 9003
    targetPort: 3000
  selector:
    propel.kubera.mayadata.io/app-name: propel-server
    propel.kubera.mayadata.io/is-server: "true"
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  labels:
    propel.kubera.mayadata.io/is-server: "true"
  name: kubera-propel-ingress
  namespace: kubera.namespace
spec:
  rules:
  - host: kubera.domain
    http:
      paths:
      - backend:
          serviceName: propel-server
          servicePort: 9002
        path: kubera.product.path/api/graphql/(.*)
      - backend:
          serviceName: propel-webapp
          servicePort: 9091
        path: kubera.product.path/(.*)
