name: Push images to docker
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Run chart-releaser
        uses: actions/checkout@v2
      - shell: bash
        run: |
          img_tag=""
          array=(`echo ${GITHUB_REF} | sed 's/\//\n/g'`)
          if [ ${array[1]} == "tags" ] 
          then
              echo "tag build"
              sed -i '/tag: /s/:.*$/: $IMG_TAG/' ./manifest/helm/charts/values.yaml
              helm package ./manifest/helm/charts
              ls 
              cat ./manifest/helm/charts/values.yaml
          else
              echo "non tag build"
              sed 's/name: kubera-propel/name: kubera-propel-ci/g' -i ./manifest/helm/charts/Chart.yaml
              sed -i '/tag: /s/:.*$/: $IMG_TAG/' ./manifest/helm/charts/values.yaml
              helm package ./manifest/helm/charts
              ls 
              cat ./manifest/helm/charts/values.yaml
              img_tag=${GITHUB_REF#refs/*/}-ci
          fi
          # This is a condition where image tag looks like "pull/<pullrequest-name>" during pull request build
          NEW_IMG_TAG=`echo $img_tag | sed "s/\//-/g"`
          echo $NEW_IMG_TAG
          echo export IMG_TAG=$NEW_IMG_TAG > env-vars