name: Push images to docker
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Run chart-releaser
        uses: actions/checkout@v2
      - shell: bash
        run: |
          img_tag=""
          array=(`echo ${GITHUB_REF} | sed 's/\//\n/g'`)
          if [ ${array[1]} == "tags" ] 
          then
              echo "tag build"
              sed -i "/tag: /s/:.*$/: $IMG_TAG/" ./manifest/helm/charts/values.yaml
              helm package ./manifest/helm/charts
              git clone https://${user}:${pass}@github.com/mayadata-io/${REPO}.git
              cd  ${REPO}
              git checkout gh-pages
              mkdir tmp
              mv ../*.tgz ./tmp
              helm repo index --url http://asset.mayadata.io/charts/ --merge ./index.yaml tmp
              mv tmp/index.yaml .
          else
              echo "non tag build"
              sed "s/name: kubera-propel/name: kubera-propel-ci/g" -i ./manifest/helm/charts/Chart.yaml
              sed -i "/tag: /s/:.*$/: $IMG_TAG/" ./manifest/helm/charts/values.yaml
              helm package ./manifest/helm/charts
              git clone https://${user}:${pass}@github.com/mayadata-io/${REPO}.git
              cd  ${REPO}
              git checkout gh-pages
              mkdir tmp
              mv ../*.tgz ./tmp
              helm repo index --url http://asset.mayadata.io/charts/ --merge ./index.yaml tmp
              mv tmp/index.yaml .
          fi
      - name: Upload tar to  S3 bucket
        uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: s3 cp ./tmp/  s3://asset.mayadata.io/charts/ --recursive --acl public-read
        env:
          # Make sure to add the secrets in the repo settings page
          # AWS_REGION is set to us-east-1 by default
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          rm -rf tmp
          git add .
          git commit -m "release new charts"
          git push https://$(git_token)@github.com/mayadata-io/${REPO}.git --all
          